name: Financial Reports

on:
  schedule:
    - cron: '0 9 * * 1'  # Weekly on Monday at 9 AM UTC
    - cron: '0 9 1 * *'  # Monthly on 1st at 9 AM UTC
  workflow_dispatch:
    inputs:
      report_type:
        description: 'Type of report to generate'
        required: true
        default: 'monthly'
        type: choice
        options:
          - monthly
          - weekly
      year:
        description: 'Year (YYYY) - Required for monthly report'
        required: false
        type: string
      month:
        description: 'Month (1-12) - Required for monthly report'
        required: false
        type: string

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run weekly report
      if: github.event.schedule == '0 9 * * 1' || (github.event_name == 'workflow_dispatch' && github.event.inputs.report_type == 'weekly')
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        REPORT_EMAIL: ${{ secrets.REPORT_EMAIL }}
      run: python automated_reports.py weekly
        
    - name: Run monthly report
      if: github.event.schedule == '0 9 1 * *' || (github.event_name == 'workflow_dispatch' && github.event.inputs.report_type == 'monthly')
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        REPORT_EMAIL: ${{ secrets.REPORT_EMAIL }}
      run: python automated_reports.py monthly
        
    - name: Run on-demand monthly report
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.report_type == 'monthly' && github.event.inputs.year != '' && github.event.inputs.month != ''
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        REPORT_EMAIL: ${{ secrets.REPORT_EMAIL }}
      run: python main.py monthly --year ${{ github.event.inputs.year }} --month ${{ github.event.inputs.month }} 